src/objects/KeyboardShortcuts_CF__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Keyboard Shortcuts for CustomFramework.</description>
    <fields>
        <fullName>JSCode_CF__c</fullName>
        <description>JS Code</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>JS Code</inlineHelpText>
        <label>JS Code</label>
        <type>TextArea</type>
    </fields>
    <label>KeyboardShortcuts</label>
</CustomObject>

src/classes/FrameworkBaseController_CF.cls
/**
 * Support class for Custom Framework operations.
 * <p /><p />
 * @author Gabriel Coronel
 */
public with sharing class FrameworkBaseController_CF extends StaticVariablesClass_CF {
    
    /**
     * Constructor fo the class.
     */
    public FrameworkBaseController_CF(ApexPages.StandardController controller) {}
    
    /**
     * Constructor fo the class.
     */
    public FrameworkBaseController_CF() {}

    /**
     * Obtain elements from Keyboard Shortcuts.
     */
    public Map<String, String> mapAvailableKeyboardShortcuts {
        get {
            Map<String, String> mapResult = new Map<String, String>();
            for(KeyboardShortcuts_CF__c objKeyboardShortcuts : KeyboardShortcuts_CF__c.getAll().values()) {
                if(String.IsNotBlank(objKeyboardShortcuts.JSCode_CF__c)) {
                    mapResult.put(objKeyboardShortcuts.Name, objKeyboardShortcuts.JSCode_CF__c);
                }
            }
            return mapResult;
        }
    }
}